/**
 * English copy — the canonical shape. `types.ts` derives `type Copy = typeof en`,
 * so `ka.ts` must match this structure exactly.
 *
 * Rich-text fragments use a discriminated-union array (`RichPart[]`) so
 * components can render inline bold/accent without HTML in strings.
 */

export type RichPart = string | { bold: string } | { accent: string };

export const en = {
  meta: {
    title: 'Xarji · Self-hosted expense tracker for Georgia',
    description:
      'Xarji reads your sms transactions into a calm, fast dashboard. Self-hosted. Free.',
  },

  nav: {
    brandTagline: 'ხარჯი',
    sourceLabel: 'Source',
    downloadCta: 'Download',
    localeSwitchAria: 'Switch language',
    links: [
      { label: 'Product',      href: '#product' },
      { label: 'How it works', href: '#how' },
      { label: 'Download',     href: '#download' },
      { label: 'FAQ',          href: '#faq' },
    ],
  },

  hero: {
    badgeSuffix: 'out now',
    titleLine1: 'Your bank sends SMS.',
    titleLine2Pre: 'Xarji builds the ',
    titleLine2Accent: 'dashboard',
    titleLine2Post: '.',
    subhead: [
      'A self-hosted personal-finance tracker for Georgia. Reads payment SMS from ',
      { bold: 'Bank of Georgia' },
      ' and ',
      { bold: 'TBC' },
      ' today — parses every transaction locally, categorizes, visualises. No upload. No scraping. Your data never leaves your machine.',
    ] as RichPart[],
    ctaPrimary: 'Download for macOS',
    ctaSecondary: 'See how it works',
    checks: [
      { title: 'Fully open source', sub: 'MIT license' },
      { title: 'Your machine only', sub: 'No cloud accounts' },
      { title: 'Works offline',     sub: 'After first read' },
    ],
    sms: {
      messagesAppLabel: 'Messages.app · now',
      smsBadge: 'SMS',
      stageReceived: 'SMS received',
      stageParsing: 'Parsing…',
      stageParsed: 'Parsed ✓',
      labelAutoCategory: 'Auto-category',
      labelBank: 'Bank',
      labelStored: 'Stored',
      valueStored: 'Local',
      bankLabels: { SOLO: 'BOG Solo', TBC: 'TBC Bank' },
      messages: [
        {
          raw: 'გადახდა: GEL47.80\nWOLT.GE / 20261\nბარათი: VISA *1423\n21.04.26 · 19:42',
          merchant: 'Wolt · Delivery', amount: 47.80, cat: 'Food & Drink',
          color: '#ff8a5c', icon: 'W', time: '19:42', bank: 'SOLO' as const,
        },
        {
          raw: 'გადახდა: GEL12.40\nSOCAR PETROL 17\nVISA *1423\n21.04.26 · 12:08',
          merchant: 'Socar · Fuel', amount: 12.40, cat: 'Transport',
          color: '#6aa3ff', icon: 'S', time: '12:08', bank: 'TBC' as const,
        },
        {
          raw: 'გადახდა: GEL256.00\nGOODWILL SAR #4\nVISA *1423\n20.04.26 · 21:14',
          merchant: 'Goodwill', amount: 256.00, cat: 'Groceries',
          color: '#4bd9a2', icon: 'G', time: '21:14', bank: 'SOLO' as const,
        },
      ],
    },
  },

  why: {
    eyebrow: 'The problem',
    titlePre: "If you live in Georgia, you don't have a ",
    titleAccent: 'real',
    titlePost: ' expense tracker.',
    intro: {
      prefix:
        'Not one Georgian bank exposes a public transaction API. Nothing you can build on. Nothing ',
      monarchText: 'Monarch',
      monarchUrl: 'https://www.monarchmoney.com',
      between: ', ',
      copilotText: 'Copilot',
      copilotUrl: 'https://copilot.money',
      suffix:
        " or any of the tools the rest of the world uses can plug into. And the analytics in the native Georgian banking apps? No custom categories, no advanced filters, no budget limits and I don’t know why, but they never worked for me. It always felt like they were hallucinating my budgets.",
    },
    cards: [
      {
        tag: '01 · The gap',
        title: 'No API. Anywhere.',
        body: 'BOG, TBC and others - neither publishes a transactions endpoint. No OAuth, no OFX, no Plaid. You cannot programmatically read your own money.',
        stat: '0',
        statLabel: 'Georgian banks with a public API',
      },
      {
        tag: '02 · The walls',
        title: 'Native apps are a dead end.',
        body: "Fixed categories you can't rename. No cross-bank view. Exports that stop at last month. Fine for checking balances, useless for actually understanding your spending.",
        stat: '✕',
        statLabel: 'Custom categories, filters, or trends',
      },
      {
        tag: '03 · The hack',
        title: 'But the SMS are already there.',
        body: 'Every Georgian bank sends a structured SMS the instant you tap your card. If you mirror those SMS from your phone to Messages.app on macOS, the data is sitting in a local SQLite file - just waiting to be proceed.',
        stat: '100%',
        statLabel: 'Of transactions, already on your Mac',
      },
    ],
    aha: {
      eyebrow: 'The realisation',
      quoteLine1: '"If SMS notifications are on, every transaction is already in my pocket.',
      quoteLine2: 'I just need to open my laptop."',
      body:
        "macOS already mirrors iPhone SMS into a local SQLite database. Every payment confirmation, every declined card, every card-on-file charge — it's all there, timestamped, in plain text. Xarji reads it, parses it, and builds the dashboard the banks refused to.",
      tagline: 'A little bit hacky. Entirely local. Works whether anyone likes it or not.',
      flow: {
        iphoneLabel: 'Your iPhone',
        iphoneSub: 'Bank SMS arrives',
        iphoneMeta: 'BOG / TBC',
        iphoneToMac: 'iCloud Messages · Forwarding on',
        macLabel: 'Messages.app on Mac',
        macSub: 'SMS mirrored to local SQLite',
        macMeta: '~/Library/Messages/chat.db',
        macToXarji: 'Read-only parse · never leaves Mac',
        xarjiLabel: 'Xarji',
        xarjiSub: 'Categorized · charted · yours',
        xarjiMeta: 'InstantDB · local',
      },
    },
  },

  product: {
    eyebrow: 'The dashboard',
    title: 'Built to be lived in.',
    subtitle:
      "A calm dark interface, one coral accent, and data you can read at a glance. Six screens cover everything from today's coffee to six months of trend.",
    browserBar: 'xarji · localhost:3000',
    screens: [
      { name: 'Overview',     sub: 'Today · month · trend' },
      { name: 'Transactions', sub: '713 parsed, filter & search' },
      { name: 'Categories',   sub: '9 buckets, auto-learn' },
      { name: 'Merchants',    sub: 'Who you paid, ranked' },
      { name: 'Signals',      sub: 'Anomalies & declines' },
      { name: 'Manage',       sub: 'Banks, preferences, data' },
    ],
    annotations: [
      'Category donut centered with legend beneath',
      'Live transactions — parsed from Messages.app',
      '9-month trend with rounded edges',
    ],
    mock: {
      greeting: 'Good evening, Nika',
      heroTitle: 'April, at a glance',
      ranges: ['Today', 'Week', 'Month', 'Year'],
      activeRange: 'Month',
      spentLabel: 'Spent this month · GEL',
      amountWhole: '6,650',
      amountDecimal: '.70',
      amountDelta: '+₾812 vs March · 21 days · 94 transactions',
      dailyAvgLabel: 'Daily avg',
      dailyAvgValue: '₾317',
      dailyAvgSub: 'low ₾48 · high ₾742',
      declinedLabel: 'Declined',
      declinedValue: '4',
      declinedSub: '2× insufficient · 1× blocked',
      spendingMixLabel: 'Spending mix',
      spendingMix: [
        { c: '#ff8a5c', n: 'Food & Drink', p: 32 },
        { c: '#4bd9a2', n: 'Groceries',    p: 22 },
        { c: '#6aa3ff', n: 'Transport',    p: 14 },
        { c: '#b38df7', n: 'Home',         p: 12 },
      ],
      recentLabel: 'Today & recent',
      liveBadge: '● Live',
      recent: [
        { ic: 'W', m: 'Wolt · Delivery',  c: 'Food & Drink', co: '#ff8a5c', a: 47.80,  t: '19:42' },
        { ic: 'S', m: 'Socar · Fuel',     c: 'Transport',    co: '#6aa3ff', a: 12.40,  t: '12:08' },
        { ic: 'G', m: 'Goodwill',         c: 'Groceries',    co: '#4bd9a2', a: 256.00, t: 'Yest 21:14' },
        { ic: 'A', m: 'Aversi Pharmacy',  c: 'Health',       co: '#b38df7', a: 18.50,  t: 'Yest 14:02' },
      ],
      sidebar: [
        { g: '◉', n: 'Overview',     a: true  },
        { g: '≡', n: 'Transactions', a: false },
        { g: '◐', n: 'Categories',   a: false },
        { g: '◆', n: 'Merchants',    a: false },
        { g: '✦', n: 'Signals',      a: false },
        { g: '⚙', n: 'Manage',       a: false },
      ],
      donutLabelTop: 'APR',
      donutLabelBottom: '₾6.6k',
    },
  },

  features: {
    eyebrow: 'Why Xarji',
    title: 'Private by design',
    subtitle: 'Every decision here is shaped by one rule: your transactions stay on your machine.',
    items: [
      { ic: '◉', t: 'Self-hosted. Full stop.',
        d: 'The DMG installs a local app. You create your own InstantDB instance, you control your data.' },
      { ic: '✉', t: 'Reads SMS, never scrapes.',
        d: 'Xarji parses the same payment SMS your bank already sends. No API keys, no login, no screen-scraping scripts.' },
      { ic: '◈', t: 'Made for Georgian banks.',
        d: 'Today: Bank of Georgia (Solo SMS) and TBC. Coming: Liberty, Basis, ProCredit, Credo, Terabank, Cartu, Halyk, VTB, PASHA, Isbank, Ziraat, Silk Road.' },
      { ic: '⬢', t: 'Auto-learning categories.',
        d: 'Assign "WOLT.GE" to Food once — Xarji remembers. Merchant variants roll up automatically.' },
      { ic: '∆', t: 'Anomalies & signals.',
        d: 'Spotting unusual amounts, duplicate charges, and declined payments before you notice them.' },
      { ic: '⇪', t: 'Export anytime.',
        d: 'Full CSV / JSON export. Your data is yours — open format, plain text, portable forever.' },
    ],
  },

  how: {
    eyebrow: 'How it works',
    title: 'Three steps',
    stepLabel: 'STEP',
    steps: [
      { n: '01', t: 'Install & grant SMS access',
        d: 'Xarji asks macOS for read access to your Messages.app database' },
      { n: '02', t: 'Parse every bank SMS',
        d: 'Parsers for Bank of Georgia (Solo) and TBC turn SMS into structured transactions: merchant, amount, card, timestamp.' },
      { n: '03', t: 'Live dashboard',
        d: 'InstantDB stores locally, syncs instantly across your windows.' },
    ],
    banks: {
      eyebrow: 'Supported banks',
      title: 'Built on real Georgian bank SMS.',
      subtitle: 'Two banks work today. The rest are on the roadmap — ranked by the asset table on Wikipedia.',
      supportedLabel: 'Working today',
      plannedLabel: 'On the roadmap',
      supported: [
        { k: 'BOG', n: 'Bank of Georgia', c: '#ffc83d', sub: 'Solo SMS · parser · live' },
        { k: 'TBC', n: 'TBC Bank',        c: '#00aaff', sub: 'TBC SMS · parser · live' },
      ],
      planned: [
        { k: 'LIB', n: 'Liberty Bank' },
        { k: 'BAS', n: 'Basis Bank' },
        { k: 'PRC', n: 'ProCredit Bank' },
        { k: 'CRD', n: 'Credo Bank' },
        { k: 'TER', n: 'Terabank' },
        { k: 'CRT', n: 'Cartu Bank' },
        { k: 'HLK', n: 'Halyk Bank' },
        { k: 'VTB', n: 'VTB Georgia' },
        { k: 'PSH', n: 'PASHA Bank' },
        { k: 'ISB', n: 'Isbank' },
        { k: 'ZIR', n: 'Ziraat Bank' },
        { k: 'SLK', n: 'Silk Road Bank' },
      ],
    },
  },

  download: {
    eyebrow: 'Get it',
    title: 'One download',
    latestBadge: 'Latest',
    xarjiForPre: 'Xarji for ',
    xarjiForAccent: 'macOS',
    releasedPrefix: 'Released',
    requires: 'Apple Silicon',
    dmgCta: 'Download Xarji.dmg',
    signedNotarized: '· signed · notarized',
    changelogLabel: 'CHANGELOG',
    whatsNewPrefix: "What's new in ",
    releaseNotes: [
      'AI Assistant can now create categories and move merchants between them — "make a Coffee shops category and put my Skola transactions there" just works',
      'Assistant remembers prior turns in a conversation, so follow-ups have context',
      'Interactive charts: hover any chart for a vs-prior-period tooltip, click a slice or bar to drill down to filtered transactions',
      'Today / Week / Month / Year / Custom range buttons now filter every page',
      '"Sync now" button under Manage → Data sources for on-demand SMS re-reads',
      'Light mode polish: cold-load no longer flashes dark first',
      'Demo mode (?demo=1 in dev) with a rich canned dataset for screencasts',
    ],
    previousLabel: 'Previous releases',
    priorDownloadLink: 'Download →',
    priorSummaries: {
      '0.2.5': 'Multi-currency totals · NBG exchange rate API · TBC parser fix',
      '0.2.4': 'Install as native macOS app · service-unreachable splash · web app manifest',
      '0.2.3': 'Animated onboarding wizard · post-setup Welcome flash fixed',
      '0.2.2': 'Release-pipeline fixes',
      '0.2.1': 'Release-pipeline fixes',
      '0.2.0': 'Bun-compiled single binary · browser onboarding · menu-bar macOS shell',
      '0.1.1': 'Ink dashboard rebuild · multi-bank parser refactor',
    },
    fallbackPrefix: 'Looking for Linux or Windows? ',
    fallbackLink: 'See FAQ →',
  },

  faq: {
    eyebrow: 'FAQ',
    title: 'Questions, answered.',
    items: [
      { q: 'Is Xarji really self-hosted? Where is my data?',
        a: 'Entirely on your Mac. Xarji uses an InstantDB instance that you create on their free tier — the credentials live in `~/.xarji/config.json`, no cloud account of ours sits between you and your data. A local JSON backup at `~/.xarji/transactions.json` is the last line of defense. There is no Xarji server, no telemetry. If you uninstall the app, your data is yours to keep or delete.' },
      { q: 'How does it read my bank SMS?',
        a: 'macOS Messages.app stores received SMS in a local SQLite database (`~/Library/Messages/chat.db`) when iPhone Stores messages in iCloud and Mac messages app is using same account. Xarji asks for read access to that file, parses only payment SMS from recognised Georgian bank senders, and ignores everything else.' },
      { q: 'Which banks are supported?',
        a: 'Today: **Bank of Georgia (Solo SMS)** and **TBC Bank**. Parsers for the other 12 major Georgian banks — Liberty, Basis, ProCredit, Credo, Terabank, Cartu, Halyk, VTB Georgia, PASHA, Isbank, Ziraat, Silk Road — are on the roadmap. If your bank isn\'t yet supported and you\'re willing to share anonymised sample SMS, open an issue on GitHub and we\'ll prioritise it.' },
      { q: 'What about Windows or Linux?',
        a: 'Not yet — Xarji relies on macOS\'s native SMS mirroring from iPhone, which Windows and Linux don\'t have. A Linux build for users with Android-SMS-bridge setups is being evaluated.' },
      { q: 'Why InstantDB?',
        a: 'We needed a local-first database that syncs instantly across the app\'s windows and tabs, with reactive queries. InstantDB fit perfectly — each user creates their own free-tier app, provides the credentials during onboarding, and the service writes straight there. No Xarji-owned backend sits in the middle.' },
      { q: 'Can I export my data?',
        a: 'Yes — full CSV and JSON export of transactions, categories, and merchants. Plain text, no lock-in.' },
      { q: 'Is it open source?',
        a: 'Yes, MIT licensed. Source on GitHub. Contributions especially new bank parsers very welcome.' },
      { q: 'Does Xarji work offline?',
        a: 'Mostly. Xarji reads SMS without any network, syncing to your InstantDB needs a connection. Parsed transactions queue locally and sync when you\'re back online. But you can process already synced data without needing internet connection' },
      { q: 'How much does it cost?',
        a: 'Free. Forever. No premium tier. If you want to support development, star the repo or send a PR. https://github.com/tornikegomareli/Xarji' },
    ],
  },

  newsletter: {
    eyebrow: 'Stay posted',
    titlePre: 'Release notes, ',
    titleAccent: 'quietly',
    titlePost: '.',
    body:
      'One short email when a new version drops, or a new bank gets supported. No marketing, no drip campaigns, no "hey, haven\'t seen you in a while!" — promise. Unsubscribe in one click.',
    emailPlaceholder: 'your@email.com',
    subscribeCta: 'Subscribe',
    loadingCta: 'Subscribing…',
    successTitle: "You're in. Talk soon.",
    successSubPre: 'We sent a confirmation to ',
    successSubPost: '. Click the link to seal the deal.',
    errorTitle: "Couldn't reach the newsletter service.",
    errorSub: 'Give it a second and try again.',
    trustNote: 'We store your email on the same self-hosted principles. No Mailchimp, no trackers.',
  },

  techStack: {
    eyebrow: 'Built with',
    items: [
      { name: 'InstantDB', role: 'Local-first database', link: 'https://instantdb.com' },
      { name: 'React',     role: 'Dashboard UI',         link: 'https://react.dev' },
      { name: 'Bun',       role: 'Service runtime',      link: 'https://bun.sh' },
      { name: 'SwiftPM',   role: 'Menu-bar app',         link: 'https://www.swift.org/documentation/package-manager/' },
    ],
  },

  footer: {
    brand: 'Xarji · ხარჯი',
    madeIn: 'Made in Tbilisi · MIT license · © 2026',
    productCol: {
      title: 'Product',
      links: [
        { label: 'Overview',     href: '#product' },
        { label: 'How it works', href: '#how' },
        { label: 'Download',     href: '#download' },
        { label: 'Changelog',    href: '#download' },
      ],
    },
    resourcesCol: {
      title: 'Resources',
      faqLabel: 'FAQ',
      githubLabel: 'GitHub',
      instantdbLabel: 'InstantDB',
      bugLabel: 'Report a bug',
    },
    legalCol: {
      title: 'Legal',
      licenseLabel: 'License · MIT',
      sourceLabel: 'Source',
    },
    notAffiliated: 'Not affiliated with any bank. Georgian Lari rates via NBG.',
  },
};
